name: Build Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Ensure Dependencies
        run: |
          go mod tidy

      - name: Build Binary
        working-directory: ./
        run: |
          make build-static

      - name: Create Git Tag
        run: |
          git tag v1.0.0
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/strangelove-ventures/bech32cli.git v1.0.0

      - name: Upload AMD64 Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bech32-amd64
          path: build/bech32-amd64

      - name: Upload ARM64 Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bech32-arm46
          path: build/bech32-arm46

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/bech32-amd64
            build/bech32-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

