name: Build Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build Binary
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bech32-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Binaries as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bech32-${{ matrix.os }}-${{ matrix.arch }}
          path: bech32-${{ matrix.os }}-${{ matrix.arch }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bech32-${{ matrix.os }}-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh release upload "v${{ github.run_number }}" bech32-${{ matrix.os }}-${{ matrix.arch }} --repo ${{ github.repository }}
