name: Build Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Build Binary
        run: |
          make build-static

      - name: Upload Binaries as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bech32-amd64
          path: build/bech32-amd64

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/bech32-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

